---
Name: ecommerce_stockcontrol
Before: 'app/*'
After: 'framework/*','cms/*', 'ecommerce/*'
---
Sunnysideup\Ecommerce\Pages\Product:
  extensions:
    - Sunnysideup\EcommerceStockControl\Decorators\BuyableStockDecorator
Sunnysideup\EcommerceStockControl\Decorators\BuyableStockDecorator:
  buyables:
    - Sunnysideup\Ecommerce\Pages\Product
